### ISSUE TITLE
Reflected XSS #security

### ISSUE THREAD

**Issue by psie** [Crunchify/Facebook-Members#1]
Hi, you might want to fix the security issue at https://github.com/Crunchify/Facebook-Members/blob/master/includes/settings-page.php#L10

Cheers,

PS

**Comment by Crunchify** [comment]
@psie thanks for reporting bug.

Could you please check and confirm changes related to this: https://github.com/Crunchify/Facebook-Members/commit/f4931ba88e47f809c7638cd19554c94047ac5124

**Comment by psie** [comment]
Looks cool, thanks!
